name: orbench
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pillow
  - libtiff
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - pip:
      - accelerate
      - sentencepiece
      - safetensors
      - hf_xet
      - git+https://github.com/huggingface/transformers@v4.51.3-LlamaGuard-preview
